### ISSUE TITLE
新建一个zh-cn目录将中文介绍也加入到ROS维基

### ISSUE THREAD

**Issue by lazyparser** [XbotGroup/xbot_roswiki#6]
看到ROS的wiki上有中文的介绍，我们可以优先做一下中文的，估计会快一些。

**Comment by DinnerHowe** [comment]
可是我了解的是中文基本没什么人看

**Comment by lazyparser** [comment]
或许现在参与的中国人不错，不过暂时的，那是因为我们还没有开始在国内发力 :)

**Comment by yowlings** [comment]
这个倒不用太着急,先把英文的做完吧,难度也不大,一个版本有了另一个版本就不难了.可能英文的显得高大上一点吧,中文的后面还是会做的.
